# docker-compose.yml
version: '3'
services:
    backend:
        container_name: backend
        build: ./backend
        ports:
            - "5000:5000"
    frontend:
        container_name: frontend
        build: ./frontend
        restart: unless-stopped
        ports:
            - "8080:8080"
